**Importing Data**

In [ ]:
import pandas as pd
df_train = pd.read_parquet('/content/train.parquet')
test = pd.read_parquet('/content/test.parquet')

**Finding shape of Dataset**

In [ ]:
df_train.shape

(3220868, 3)

In [ ]:
test.shape

(1065524, 3)

**Observing the Data**

In [ ]:
df_train.head(20)

                             Patient-Uid       Date           Incident
0   a0db1e73-1c7c-11ec-ae39-16262ee38c7f 2019-03-09  PRIMARY_DIAGNOSIS
1   a0dc93f2-1c7c-11ec-9cd2-16262ee38c7f 2015-05-16  PRIMARY_DIAGNOSIS
3   a0dc94c6-1c7c-11ec-a3a0-16262ee38c7f 2018-01-30     SYMPTOM_TYPE_0
4   a0dc950b-1c7c-11ec-b6ec-16262ee38c7f 2015-04-22        DRUG_TYPE_0
8   a0dc9543-1c7c-11ec-bb63-16262ee38c7f 2016-06-18        DRUG_TYPE_1
9   a0dc9577-1c7c-11ec-8b4d-16262ee38c7f 2019-12-16        DRUG_TYPE_1
11  a0dc95c6-1c7c-11ec-8e77-16262ee38c7f 2020-02-07        DRUG_TYPE_1
12  a0dc95f9-1c7c-11ec-b968-16262ee38c7f 2019-08-01        DRUG_TYPE_1
14  a0dc962a-1c7c-11ec-8a51-16262ee38c7f 2017-06-20        DRUG_TYPE_1
16  a0dc9659-1c7c-11ec-a91e-16262ee38c7f 2015-11-25        DRUG_TYPE_2
17  a0dc9689-1c7c-11ec-9ca7-16262ee38c7f 2016-08-07        TEST_TYPE_0
19  a0dc96ca-1c7c-11ec-89e9-16262ee38c7f 2016-09-14        DRUG_TYPE_2
20  a0dc96fb-1c7c-11ec-82ed-16262ee38c7f 2018-11-02        DRUG_TYPE_3
21  a0dc972c-1c7c-11ec-a850-16262ee38c7f 2015-07-04        DRUG_TYPE_1
24  a0dc975b-1c7c-11ec-bb4a-16262ee38c7f 2019-04-03        DRUG_TYPE_2
25  a0dc978b-1c7c-11ec-9956-16262ee38c7f 2018-03-01        DRUG_TYPE_3
26  a0dc97bd-1c7c-11ec-a9d4-16262ee38c7f 2015-08-02  PRIMARY_DIAGNOSIS
27  a0dc97ee-1c7c-11ec-b241-16262ee38c7f 2016-01-27        DRUG_TYPE_4
28  a0dc981e-1c7c-11ec-b4aa-16262ee38c7f 2017-09-21        DRUG_TYPE_5
30  a0dc984d-1c7c-11ec-b4de-16262ee38c7f 2018-01-13     SYMPTOM_TYPE_0

**Checking Null Values**

In [ ]:
df_train.isnull().sum()

Patient-Uid    0
Date           0
Incident       0
dtype: int64

**Dropping Date Column**

In [ ]:
df_train1=df_train.drop('Date',axis=1)
df_train1.head()

                            Patient-Uid           Incident
0  a0db1e73-1c7c-11ec-ae39-16262ee38c7f  PRIMARY_DIAGNOSIS
1  a0dc93f2-1c7c-11ec-9cd2-16262ee38c7f  PRIMARY_DIAGNOSIS
3  a0dc94c6-1c7c-11ec-a3a0-16262ee38c7f     SYMPTOM_TYPE_0
4  a0dc950b-1c7c-11ec-b6ec-16262ee38c7f        DRUG_TYPE_0
8  a0dc9543-1c7c-11ec-bb63-16262ee38c7f        DRUG_TYPE_1

**One-Hot Encoding**

In [ ]:
train_data=pd.get_dummies(df_train['Incident'], drop_first=True)
train_data

,DRUG_TYPE_1,DRUG_TYPE_10,DRUG_TYPE_11,DRUG_TYPE_12,DRUG_TYPE_13,DRUG_TYPE_14,DRUG_TYPE_15,DRUG_TYPE_16,DRUG_TYPE_17,DRUG_TYPE_18,...,SYMPTOM_TYPE_7,SYMPTOM_TYPE_8,SYMPTOM_TYPE_9,TARGET DRUG,TEST_TYPE_0,TEST_TYPE_1,TEST_TYPE_2,TEST_TYPE_3,TEST_TYPE_4,TEST_TYPE_5
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29080886,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
29080897,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
29080900,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
29080903,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
29080911,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

**Concatinating Data Frames**

In [ ]:
df_train2=pd.concat([df_train1,train_data],axis=1)
df_train2.head()

,Patient-Uid,Incident,DRUG_TYPE_1,DRUG_TYPE_10,DRUG_TYPE_11,DRUG_TYPE_12,DRUG_TYPE_13,DRUG_TYPE_14,DRUG_TYPE_15,DRUG_TYPE_16,...,SYMPTOM_TYPE_7,SYMPTOM_TYPE_8,SYMPTOM_TYPE_9,TARGET DRUG,TEST_TYPE_0,TEST_TYPE_1,TEST_TYPE_2,TEST_TYPE_3,TEST_TYPE_4,TEST_TYPE_5
0,a0db1e73-1c7c-11ec-ae39-16262ee38c7f,PRIMARY_DIAGNOSIS,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,a0dc93f2-1c7c-11ec-9cd2-16262ee38c7f,PRIMARY_DIAGNOSIS,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,a0dc94c6-1c7c-11ec-a3a0-16262ee38c7f,SYMPTOM_TYPE_0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,a0dc950b-1c7c-11ec-b6ec-16262ee38c7f,DRUG_TYPE_0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8,a0dc9543-1c7c-11ec-bb63-16262ee38c7f,DRUG_TYPE_1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

**Dropping Incident Column**

In [ ]:
df_train3=df_train2.drop('Incident',axis=1)
df_train3.head()

,Patient-Uid,DRUG_TYPE_1,DRUG_TYPE_10,DRUG_TYPE_11,DRUG_TYPE_12,DRUG_TYPE_13,DRUG_TYPE_14,DRUG_TYPE_15,DRUG_TYPE_16,DRUG_TYPE_17,...,SYMPTOM_TYPE_7,SYMPTOM_TYPE_8,SYMPTOM_TYPE_9,TARGET DRUG,TEST_TYPE_0,TEST_TYPE_1,TEST_TYPE_2,TEST_TYPE_3,TEST_TYPE_4,TEST_TYPE_5
0,a0db1e73-1c7c-11ec-ae39-16262ee38c7f,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,a0dc93f2-1c7c-11ec-9cd2-16262ee38c7f,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,a0dc94c6-1c7c-11ec-a3a0-16262ee38c7f,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,a0dc950b-1c7c-11ec-b6ec-16262ee38c7f,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8,a0dc9543-1c7c-11ec-bb63-16262ee38c7f,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

**Checking the value counts in target column**

In [ ]:
df_train3['TARGET DRUG'].value_counts()

0    3153650
1      67218
Name: TARGET DRUG, dtype: int64

**Extracting the rows which Target Drug is 0**

In [ ]:
df_train_0=df_train3[df_train3['TARGET DRUG']==0]
df_train_0.shape

(3153650, 57)

**Extracting the rows which Target Drug is 1**

In [ ]:
df_train_1=df_train3[df_train3['TARGET DRUG']==1]
df_train_1.shape

(67218, 57)

**Sampling**

In [ ]:
df_train0=df_train_0.sample(n=67218)

**Grouping Patient-ID**

In [ ]:
# Grouping the dataset of target 0 by patient uid
df_train0_data=df_train0.groupby(by='Patient-Uid',as_index=False).mean()

In [ ]:
df_train0_data.head()

,Patient-Uid,DRUG_TYPE_1,DRUG_TYPE_10,DRUG_TYPE_11,DRUG_TYPE_12,DRUG_TYPE_13,DRUG_TYPE_14,DRUG_TYPE_15,DRUG_TYPE_16,DRUG_TYPE_17,...,SYMPTOM_TYPE_7,SYMPTOM_TYPE_8,SYMPTOM_TYPE_9,TARGET DRUG,TEST_TYPE_0,TEST_TYPE_1,TEST_TYPE_2,TEST_TYPE_3,TEST_TYPE_4,TEST_TYPE_5
0,a0db1e73-1c7c-11ec-ae39-16262ee38c7f,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
1,a0dc93f2-1c7c-11ec-9cd2-16262ee38c7f,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,a0dc94c6-1c7c-11ec-a3a0-16262ee38c7f,0.0,0.0,0.333333,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,a0dc950b-1c7c-11ec-b6ec-16262ee38c7f,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,a0dc9543-1c7c-11ec-bb63-16262ee38c7f,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0

**Changing Data type**

In [ ]:
df_train0_data['TARGET DRUG']=df_train0_data['TARGET DRUG'].astype(int)

In [ ]:
df_train0_data

,Patient-Uid,DRUG_TYPE_1,DRUG_TYPE_10,DRUG_TYPE_11,DRUG_TYPE_12,DRUG_TYPE_13,DRUG_TYPE_14,DRUG_TYPE_15,DRUG_TYPE_16,DRUG_TYPE_17,...,SYMPTOM_TYPE_7,SYMPTOM_TYPE_8,SYMPTOM_TYPE_9,TARGET DRUG,TEST_TYPE_0,TEST_TYPE_1,TEST_TYPE_2,TEST_TYPE_3,TEST_TYPE_4,TEST_TYPE_5
0,a0db1e73-1c7c-11ec-ae39-16262ee38c7f,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0,1.0,0.0,0.0,0.0,0.0,0.0
1,a0dc93f2-1c7c-11ec-9cd2-16262ee38c7f,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
2,a0dc94c6-1c7c-11ec-a3a0-16262ee38c7f,0.000000,0.0,0.333333,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
3,a0dc950b-1c7c-11ec-b6ec-16262ee38c7f,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
4,a0dc9543-1c7c-11ec-bb63-16262ee38c7f,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0,0.0,1.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23119,a0f0d496-1c7c-11ec-ab26-16262ee38c7f,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
23120,a0f0d4c5-1c7c-11ec-bfec-16262ee38c7f,0.333333,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
23121,a0f0d4f4-1c7c-11ec-b144-16262ee38c7f,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
23122,a0f0d523-1c7c-11ec-89d2-16262ee38c7f,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
23123,a0f0d582-1c7c-11ec-a6c1-16262ee38c7f,0.666667,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:

df_train_1_data=df_train_1.groupby(by='Patient-Uid',as_index=False).mean()
df_train_1_data.head()

,Patient-Uid,DRUG_TYPE_1,DRUG_TYPE_10,DRUG_TYPE_11,DRUG_TYPE_12,DRUG_TYPE_13,DRUG_TYPE_14,DRUG_TYPE_15,DRUG_TYPE_16,DRUG_TYPE_17,...,SYMPTOM_TYPE_7,SYMPTOM_TYPE_8,SYMPTOM_TYPE_9,TARGET DRUG,TEST_TYPE_0,TEST_TYPE_1,TEST_TYPE_2,TEST_TYPE_3,TEST_TYPE_4,TEST_TYPE_5
0,a0e9c384-1c7c-11ec-81a0-16262ee38c7f,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
1,a0e9c3b3-1c7c-11ec-ae8e-16262ee38c7f,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
2,a0e9c3e3-1c7c-11ec-a8b9-16262ee38c7f,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
3,a0e9c414-1c7c-11ec-889a-16262ee38c7f,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
4,a0e9c443-1c7c-11ec-9eb0-16262ee38c7f,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
df_train_01_data1=df_train_1_data.drop('Patient-Uid',axis=1)

In [ ]:
df_train_01_data1.head()

,DRUG_TYPE_1,DRUG_TYPE_10,DRUG_TYPE_11,DRUG_TYPE_12,DRUG_TYPE_13,DRUG_TYPE_14,DRUG_TYPE_15,DRUG_TYPE_16,DRUG_TYPE_17,DRUG_TYPE_18,...,SYMPTOM_TYPE_7,SYMPTOM_TYPE_8,SYMPTOM_TYPE_9,TARGET DRUG,TEST_TYPE_0,TEST_TYPE_1,TEST_TYPE_2,TEST_TYPE_3,TEST_TYPE_4,TEST_TYPE_5
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
df_train_01_data01=df_train_01_data1.apply(lambda x:x.astype(float))
df_train_01_data01.head()

,DRUG_TYPE_1,DRUG_TYPE_10,DRUG_TYPE_11,DRUG_TYPE_12,DRUG_TYPE_13,DRUG_TYPE_14,DRUG_TYPE_15,DRUG_TYPE_16,DRUG_TYPE_17,DRUG_TYPE_18,...,SYMPTOM_TYPE_7,SYMPTOM_TYPE_8,SYMPTOM_TYPE_9,TARGET DRUG,TEST_TYPE_0,TEST_TYPE_1,TEST_TYPE_2,TEST_TYPE_3,TEST_TYPE_4,TEST_TYPE_5
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
df_train_01_data11=pd.concat([pd.DataFrame(df_train_1_data['Patient-Uid']),df_train_01_data01],axis=1)
df_train_01_data11.head()

,Patient-Uid,DRUG_TYPE_1,DRUG_TYPE_10,DRUG_TYPE_11,DRUG_TYPE_12,DRUG_TYPE_13,DRUG_TYPE_14,DRUG_TYPE_15,DRUG_TYPE_16,DRUG_TYPE_17,...,SYMPTOM_TYPE_7,SYMPTOM_TYPE_8,SYMPTOM_TYPE_9,TARGET DRUG,TEST_TYPE_0,TEST_TYPE_1,TEST_TYPE_2,TEST_TYPE_3,TEST_TYPE_4,TEST_TYPE_5
0,a0e9c384-1c7c-11ec-81a0-16262ee38c7f,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
1,a0e9c3b3-1c7c-11ec-ae8e-16262ee38c7f,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
2,a0e9c3e3-1c7c-11ec-a8b9-16262ee38c7f,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
3,a0e9c414-1c7c-11ec-889a-16262ee38c7f,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
4,a0e9c443-1c7c-11ec-9eb0-16262ee38c7f,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
train_data=pd.concat([df_train0_data,df_train_01_data11],axis=0)

**Final Train Dataset**

In [ ]:
train_data.head()

,Patient-Uid,DRUG_TYPE_1,DRUG_TYPE_10,DRUG_TYPE_11,DRUG_TYPE_12,DRUG_TYPE_13,DRUG_TYPE_14,DRUG_TYPE_15,DRUG_TYPE_16,DRUG_TYPE_17,...,SYMPTOM_TYPE_7,SYMPTOM_TYPE_8,SYMPTOM_TYPE_9,TARGET DRUG,TEST_TYPE_0,TEST_TYPE_1,TEST_TYPE_2,TEST_TYPE_3,TEST_TYPE_4,TEST_TYPE_5
0,a0db1e73-1c7c-11ec-ae39-16262ee38c7f,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
1,a0dc93f2-1c7c-11ec-9cd2-16262ee38c7f,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,a0dc94c6-1c7c-11ec-a3a0-16262ee38c7f,0.0,0.0,0.333333,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,a0dc950b-1c7c-11ec-b6ec-16262ee38c7f,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,a0dc9543-1c7c-11ec-bb63-16262ee38c7f,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0

**Taking xtrain and ytrain based on training data**

In [ ]:
x_train1=train_data.drop(['TARGET DRUG'],axis=1)

In [ ]:
x_train=x_train1.drop('Patient-Uid',axis=1)
x_train.head()

,DRUG_TYPE_1,DRUG_TYPE_10,DRUG_TYPE_11,DRUG_TYPE_12,DRUG_TYPE_13,DRUG_TYPE_14,DRUG_TYPE_15,DRUG_TYPE_16,DRUG_TYPE_17,DRUG_TYPE_18,...,SYMPTOM_TYPE_6,SYMPTOM_TYPE_7,SYMPTOM_TYPE_8,SYMPTOM_TYPE_9,TEST_TYPE_0,TEST_TYPE_1,TEST_TYPE_2,TEST_TYPE_3,TEST_TYPE_4,TEST_TYPE_5
0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.333333,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.333333,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0

In [ ]:
y_train=train_data['TARGET DRUG']

**Test Data**

In [ ]:
test.head()

                            Patient-Uid       Date        Incident
0  a0f9e8a9-1c7c-11ec-8d25-16262ee38c7f 2016-12-08  SYMPTOM_TYPE_0
1  a0f9e8a9-1c7c-11ec-8d25-16262ee38c7f 2018-10-17     DRUG_TYPE_0
2  a0f9e8a9-1c7c-11ec-8d25-16262ee38c7f 2017-12-01     DRUG_TYPE_2
3  a0f9e8a9-1c7c-11ec-8d25-16262ee38c7f 2018-12-05     DRUG_TYPE_1
4  a0f9e8a9-1c7c-11ec-8d25-16262ee38c7f 2017-11-04  SYMPTOM_TYPE_0

**Dropping Date column from the test data**

In [ ]:
test1=test.drop('Date',axis=1)

In [ ]:
test1.head()

                            Patient-Uid        Incident
0  a0f9e8a9-1c7c-11ec-8d25-16262ee38c7f  SYMPTOM_TYPE_0
1  a0f9e8a9-1c7c-11ec-8d25-16262ee38c7f     DRUG_TYPE_0
2  a0f9e8a9-1c7c-11ec-8d25-16262ee38c7f     DRUG_TYPE_2
3  a0f9e8a9-1c7c-11ec-8d25-16262ee38c7f     DRUG_TYPE_1
4  a0f9e8a9-1c7c-11ec-8d25-16262ee38c7f  SYMPTOM_TYPE_0

**One-Hot Encoding for Incident Column**

In [ ]:
test_data=pd.get_dummies(test['Incident'],drop_first=True)

In [ ]:
test2=pd.concat([test1,test_data],axis=1)

In [ ]:
test3=test2.drop('Incident',axis=1)

In [ ]:
test3.head(2)

,Patient-Uid,DRUG_TYPE_1,DRUG_TYPE_10,DRUG_TYPE_11,DRUG_TYPE_12,DRUG_TYPE_13,DRUG_TYPE_14,DRUG_TYPE_15,DRUG_TYPE_16,DRUG_TYPE_17,...,SYMPTOM_TYPE_6,SYMPTOM_TYPE_7,SYMPTOM_TYPE_8,SYMPTOM_TYPE_9,TEST_TYPE_0,TEST_TYPE_1,TEST_TYPE_2,TEST_TYPE_3,TEST_TYPE_4,TEST_TYPE_5
0,a0f9e8a9-1c7c-11ec-8d25-16262ee38c7f,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,a0f9e8a9-1c7c-11ec-8d25-16262ee38c7f,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
test3.shape

(1065524, 55)

In [ ]:
Test_data=test3.groupby('Patient-Uid',as_index=False).mean()

**Final Test data**

In [ ]:
Test_data.sample(4)

,Patient-Uid,DRUG_TYPE_1,DRUG_TYPE_10,DRUG_TYPE_11,DRUG_TYPE_12,DRUG_TYPE_13,DRUG_TYPE_14,DRUG_TYPE_15,DRUG_TYPE_16,DRUG_TYPE_17,...,SYMPTOM_TYPE_6,SYMPTOM_TYPE_7,SYMPTOM_TYPE_8,SYMPTOM_TYPE_9,TEST_TYPE_0,TEST_TYPE_1,TEST_TYPE_2,TEST_TYPE_3,TEST_TYPE_4,TEST_TYPE_5
5442,a0fdf587-1c7c-11ec-853b-16262ee38c7f,0.123288,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.054795,0.027397,0.0,0.000000,0.013699,0.027397,0.000000,0.0,0.0,0.0
8888,a1008233-1c7c-11ec-bf66-16262ee38c7f,0.155989,0.0,0.041783,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.002786,0.0,0.002786,0.008357,0.019499,0.000000,0.0,0.0,0.0
8794,a1007073-1c7c-11ec-8571-16262ee38c7f,0.227273,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.022727,0.090909,0.0,0.000000,0.000000,0.068182,0.022727,0.0,0.0,0.0
5662,a0fe20df-1c7c-11ec-86bc-16262ee38c7f,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0

In [ ]:
Test_data.shape

(11482, 55)

**Taking xtest from the text data**

In [ ]:
x_Test_data=Test_data.drop('Patient-Uid',axis=1)

In [ ]:
x_Test_data.head()

,DRUG_TYPE_1,DRUG_TYPE_10,DRUG_TYPE_11,DRUG_TYPE_12,DRUG_TYPE_13,DRUG_TYPE_14,DRUG_TYPE_15,DRUG_TYPE_16,DRUG_TYPE_17,DRUG_TYPE_2,...,SYMPTOM_TYPE_6,SYMPTOM_TYPE_7,SYMPTOM_TYPE_8,SYMPTOM_TYPE_9,TEST_TYPE_0,TEST_TYPE_1,TEST_TYPE_2,TEST_TYPE_3,TEST_TYPE_4,TEST_TYPE_5
0,0.054545,0.0,0.018182,0.0,0.0,0.0,0.000000,0.0,0.0,0.036364,...,0.054545,0.0,0.0,0.0,0.036364,0.000000,0.0,0.000000,0.0,0.0
1,0.230769,0.0,0.000000,0.0,0.0,0.0,0.069231,0.0,0.0,0.123077,...,0.015385,0.0,0.0,0.0,0.000000,0.000000,0.0,0.007692,0.0,0.0
2,0.362637,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.109890,...,0.000000,0.0,0.0,0.0,0.000000,0.021978,0.0,0.000000,0.0,0.0
3,0.000000,0.0,0.008772,0.0,0.0,0.0,0.000000,0.0,0.0,0.026316,...,0.000000,0.0,0.0,0.0,0.008772,0.000000,0.0,0.000000,0.0,0.0
4,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.059701,...,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.0

**Building Models**

#**Logistic Regression**

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

**Fitting the model**

In [ ]:
lr=LogisticRegression()
model_train=lr.fit(x_train,y_train)

**Accuracy Score**

In [ ]:
predict_train=lr.predict(x_train)
score=accuracy_score(predict_train,y_train)
score

0.9755369561203766

**F1- Score**

In [ ]:
from sklearn.metrics import accuracy_score, plot_roc_curve, roc_curve, roc_auc_score, confusion_matrix, f1_score
f1_score(predict_train,y_train)

0.9593204728035614

**AUROC Score**

In [ ]:
roc_auc_score(y_train, dt.predict_proba(x_train)[:, 1])

0.9366459090122816

#**Decision Tree Classifier**

In [ ]:
from sklearn.tree import DecisionTreeClassifier

dt = DecisionTreeClassifier(max_depth = 6)
dt.fit(x_train, y_train)

DecisionTreeClassifier(max_depth=6)

**AUROC Score**

In [ ]:
roc_auc_score(y_train, dt.predict_proba(x_train)[:, 1])

0.9366459090122816

#**RANDOM FOREST CLASSIFIER**

In [ ]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators= 100, max_depth = 6, max_features='sqrt')
rf.fit(x_train, y_train)
predictions = rf.predict(x_train)
acc1 = roc_auc_score(y_train, predictions)
print("Test set auc: {:.2f}".format(acc1))

Test set auc: 0.98

**AUROC Score**

In [ ]:
roc_auc_score(y_train, rf.predict_proba(x_train)[:, 1])

0.9824641065559592

#**XG BOOST CLASSIFIER**

In [ ]:
import xgboost as xgb
from sklearn.model_selection import cross_val_score
import numpy as np
for lr in [0.01,0.02,0.03,0.04,0.05,0.06,0.07,0.08,0.09,0.1,0.11,0.12,0.13,0.14,0.15,0.2,0.5,0.7,1]:
  model = xgb.XGBClassifier(learning_rate = lr, n_estimators=100, verbosity = 0) # initialise the model
  model.fit(x_train,y_train) #train the model 
  print("Learning rate : ", lr, " Train score : ", model.score(x_train,y_train), " Cross-Val score : ", np.mean(cross_val_score(model, x_train, y_train, cv=10)))

Learning rate :  0.01  Train score :  0.8835312942334913  Cross-Val score :  0.883533158131496
Learning rate :  0.02  Train score :  0.9098406055757278  Cross-Val score :  0.9098415133650588
Learning rate :  0.03  Train score :  0.9251646255154163  Cross-Val score :  0.9251654047399201
Learning rate :  0.04  Train score :  0.9351652409379039  Cross-Val score :  0.9350431517389968
Learning rate :  0.05  Train score :  0.9412579235645271  Cross-Val score :  0.9416279849421123
Learning rate :  0.06  Train score :  0.9469505815742507  Cross-Val score :  0.9479052300116011
Learning rate :  0.07  Train score :  0.9580589574743061  Cross-Val score :  0.9559363022941969
Learning rate :  0.08  Train score :  0.9592590313250046  Cross-Val score :  0.959013386367403
Learning rate :  0.09  Train score :  0.9601821650563112  Cross-Val score :  0.9598442124203895
Learning rate :  0.1  Train score :  0.9617514923995323  Cross-Val score :  0.9616596917394702
Learning rate :  0.11  Train score :  0.9638746999815373  Cross-Val score :  0.9636290077420272
Learning rate :  0.12  Train score :  0.965290171702874  Cross-Val score :  0.9648290077420272
Learning rate :  0.13  Train score :  0.9659055941904117  Cross-Val score :  0.9654753320548336
Learning rate :  0.14  Train score :  0.9658440519416579  Cross-Val score :  0.9658138030636645
Learning rate :  0.15  Train score :  0.9671056680411102  Cross-Val score :  0.9660291971494187
Learning rate :  0.2  Train score :  0.969567357991261  Cross-Val score :  0.9692601463172099
Learning rate :  0.5  Train score :  0.9771985968367284  Cross-Val score :  0.9768605346023629
Learning rate :  0.7  Train score :  0.9771985968367284  Cross-Val score :  0.9769220730639013
Learning rate :  1  Train score :  0.977044741214844  Cross-Val score :  0.9766451405166086

In [ ]:
model = xgb.XGBClassifier(learning_rate = 0.7, n_estimators=100)
model.fit(x_train,y_train) #train the model
model.score(x_train, y_train)

0.9771985968367284

**Logistic Regression** - 0.93

**Decision Tree** - 0.93

**Random Forest** - 0.98

**XG Boost** - 0.97

The best Machine Learning algorithm for Customer conversion Prediction is **RANDOM FOREST** Model

**Converting to DataFrame Based On Sample Output**

In [ ]:
predict_test=lr.predict(x_Test_data).astype(int)
predict_test

array([0, 0, 0, ..., 0, 0, 0])

In [ ]:
data=pd.DataFrame(predict_test)
data1=pd.concat([pd.DataFrame(Test_data['Patient-Uid']),data],axis=1)
data.value_counts()

0    11479
1        3
dtype: int64

In [ ]:
data1.sample(20)

                                Patient-Uid  0
488    a0fa46fb-1c7c-11ec-8ac7-16262ee38c7f  0
1144   a0fac428-1c7c-11ec-9bc7-16262ee38c7f  0
2986   a0fc2415-1c7c-11ec-bfa4-16262ee38c7f  0
10374  a10199ff-1c7c-11ec-b1a0-16262ee38c7f  0
3217   a0fc4ff6-1c7c-11ec-8e71-16262ee38c7f  0
4927   a0fd940f-1c7c-11ec-83aa-16262ee38c7f  0
9757   a101264f-1c7c-11ec-9f17-16262ee38c7f  0
7488   a0ff7963-1c7c-11ec-b36f-16262ee38c7f  0
5563   a0fe0e4d-1c7c-11ec-8c1a-16262ee38c7f  0
3546   a0fc8e27-1c7c-11ec-8d8f-16262ee38c7f  0
3268   a0fc5986-1c7c-11ec-9563-16262ee38c7f  0
9669   a10115cf-1c7c-11ec-865e-16262ee38c7f  0
9845   a10136c4-1c7c-11ec-807b-16262ee38c7f  0
5695   a0fe2717-1c7c-11ec-ac8e-16262ee38c7f  0
7112   a0ff31a5-1c7c-11ec-bb9c-16262ee38c7f  0
415    a0fa3920-1c7c-11ec-a54d-16262ee38c7f  0
1545   a0fb1072-1c7c-11ec-9c3c-16262ee38c7f  0
1862   a0fb4d08-1c7c-11ec-b4fe-16262ee38c7f  0
7277   a0ff511a-1c7c-11ec-9859-16262ee38c7f  0
6063   a0fe6c3a-1c7c-11ec-9ce2-16262ee38c7f  0

**Renaming the Column Based on Output Format**

In [ ]:
data1.rename(columns = {0:'label'}, inplace = True)

**Final Dataset**

In [ ]:
data1.head()

                            Patient-Uid  label
0  a0f9e8a9-1c7c-11ec-8d25-16262ee38c7f      0
1  a0f9e9f9-1c7c-11ec-b565-16262ee38c7f      0
2  a0f9ea43-1c7c-11ec-aa10-16262ee38c7f      0
3  a0f9ea7c-1c7c-11ec-af15-16262ee38c7f      0
4  a0f9eab1-1c7c-11ec-a732-16262ee38c7f      0

**Final DataFrame Converting to CSV File**

In [ ]:
data1.to_csv("final_submission.csv", index = False)